apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bugdrill-api.fullname" . }}
  labels:
    {{- include "bugdrill-api.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.config.env | quote }}
  SERVER_PORT: {{ .Values.config.server.port | quote }}
  SERVER_READ_TIMEOUT: {{ .Values.config.server.readTimeout | quote }}
  SERVER_WRITE_TIMEOUT: {{ .Values.config.server.writeTimeout | quote }}
  SERVER_IDLE_TIMEOUT: {{ .Values.config.server.idleTimeout | quote }}
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  DB_SSL_MODE: {{ .Values.config.database.sslMode | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  EXECUTOR_URL: {{ .Values.config.executor.url | quote }}
  JWT_ACCESS_EXPIRATION: {{ .Values.config.jwt.accessExpiration | quote }}
  JWT_REFRESH_EXPIRATION: {{ .Values.config.jwt.refreshExpiration | quote }}
