apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bugdrill-api.fullname" . }}
  labels:
    {{- include "bugdrill-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | default "postgres" | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | default "postgres" | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | default "" | quote }}
  JWT_ACCESS_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ randAlphaNum 32 | b64enc | quote }}
